### ISSUE TITLE
希望可以支持Linux(

### ISSUE THREAD

**Issue by mwx2006** [Nambers/MiraiCP#1]
希望可以支持调用Linux的so文件（

**Comment by Nambers** [comment]
有点难吧 我很少写liunx

**Comment by mwx2006** [comment]
👀其实我已经写好Linux版的了

**Comment by Nambers** [comment]
太强了

**Comment by mwx2006** [comment]
其实也就dll变成了so其他基本上没动过

**Comment by Nambers** [comment]
那也还好啦 我倒是很少用liunx 都是win

**Comment by mwx2006** [comment]
当时就是想着挂在服务器上方便点

**Comment by Nambers** [comment]
嗯也是

**Comment by Michael1015198808** [comment]
> 其实我已经写好Linux版的了

您好，请问方便PR吗，我也在Linux开发，但是动态链接的一些内容不是很清楚，include/miraicp/dllmain.cpp里面的内容不知道该如何替换

**Comment by Nambers** [comment]
> > 其实我已经写好Linux版的了
> 
> 您好，请问方便PR吗，我也在Linux开发，但是动态链接的一些内容不是很清楚，include/miraicp/dllmain.cpp里面的内容不知道该如何替换

里面的内容是dll入口点， so好像不需要单独写个入口点好像(
不过我也没写过so

**Comment by Michael1015198808** [comment]
> > > 其实我已经写好Linux版的了
> > 
> > 
> > 您好，请问方便PR吗，我也在Linux开发，但是动态链接的一些内容不是很清楚，include/miraicp/dllmain.cpp里面的内容不知道该如何替换
> 
> 里面的内容是dll入口点， so好像不需要单独写个入口点好像(
> 不过我也没写过so

我尝试直接把那个文件注释了，但是别的地方有很多__stdcall这种东西无法处理
