### ISSUE TITLE
修复MessageSource序列化问题

### ISSUE THREAD

**Issue by Nambers** [Nambers/MiraiCP#11]
目前会报错不过不影响使用 https://github.com/mamoe/mirai/issues/1086

**Comment by Nambers** [comment]
此问题要等到Mirai发布v2.6.0预计

**Comment by ARKMIO** [comment]
突然发现，还是影响使用的，每条消息只要带图片，就会因为序列化失败不触发消息回调

**Comment by Nambers** [comment]
> 突然发现，还是影响使用的，每条消息只要带图片，就会因为序列化失败不触发消息回调

喔 好像是，因为撤回信息需要用消息源撤回，而消息源我是用序列化进行传递，如果序列化失败就没传下来，我想想怎么解决

**Comment by Nambers** [comment]
mirai已修复
