### ISSUE TITLE
[bug]: e.accept()方法怎么会是拒绝请求呢？

### ISSUE THREAD

**Issue by 31207** [Nambers/MiraiCP#112]
### 问题描述

e.accept()方法怎么会是拒绝请求呢？应该是同意才对啊？？
![QQ截图20220301130821](https://user-images.githubusercontent.com/50190343/156109020-1e99d27b-01d8-42ba-b5ab-e960566d868b.png)
![QQ截图20220301130854](https://user-images.githubusercontent.com/50190343/156109041-54eafc8c-40e2-43d7-bd70-a151465227f2.png)
![QQ截图20220301130919](https://user-images.githubusercontent.com/50190343/156109069-e32874ec-341b-49a9-bbef-09d22b89481d.png)

### 日志

```text
没有报错，没有文本
```

### 版本

2.10.0

### 组件

Loader

**Comment by Nambers** [comment]
可以在下一个版本发布前先使用 https://github.com/Nambers/MiraiCP-devReleases/tree/main/%23112 这里的文件替换来解决这个问题
