### ISSUE TITLE
MiraiCP多插件加载，以及热加载

### ISSUE THREAD

**Issue by Antares0982** [Nambers/MiraiCP#113]
### 功能描述

MiraiCP loader与mcl支持多个插件加载

### 原因

目前，MiraiCP使用加载动态链接库的方式加载插件。通过将动态链接库中三个函数注册到kotlin端实现通信。但加载的第二个插件会将接口全部覆盖，同时也无法实现插件的热加载。现在考虑实现一个中间件libLoader，用于加载cpp插件并与之通信。

目前的思路：

* kotlin端链接libLoader，将配置文件路径传递给libLoader
* libLoader中使用dlopen()加载插件，并检验是否实现了入口、出口函数
* 每当有事件进入时，kotlin端将事件传递给libLoader，libLoader端并发地将event传递给所有插件。需要一个线程池来管理
* 插件可以控制自身或其他插件的开关。目前的思路是将一系列函数指针存进结构体，将结构体地址作为参数传递给所有插件，插件保存该地址，即可实现libLoader API暴露给插件
* 因为有中间件的存在，插件中可以去掉所有关于jvm部分的代码，转为使用libloader提供的一系列接口。libLoader中具体处理与jvm的交互

加载流程（可能需要修改）：
* kotlin端初始化，并通知libLoader初始化；
* libLoader获取到gvm并存储，初始化env manager，读取kotlin中的CPPLib类，初始化logger；
* 读取插件列表，打开并测试入口函数以及需要的所有符号的存在性；
* 所有有效的插件存入plugin_list，开启插件数目等同的worker并发线程并等待任务；在所有worker中添加入口函数onEnable任务（~~防止一些在入口函数中插入while循环等阻塞代码的插件阻塞整个流程~~没有必要这样实现，插件中onEnable不应阻塞）；
* 事件发生时，将事件通过插件各自对应的worker线程广播给所有启用的插件，并让插件在自身对应的线程中完成处理；
* 插件关闭的api被调用时，对应worker线程添加对应插件的onDisable任务，并dlclose()释放掉对应资源，但插件信息仍然会被保留，之后可以调用api重新启动它；
* 可以在运行时通过调用api加载之前未加载过的插件；
* kotlin端退出时，调用所有现存插件的onDisable，并释放资源。

目前libLoader准备暴露给插件的接口：
* 一组用于处理插件加载的函数指针
* 获取jnienv的函数指针
* libLoader的logger api。插件中的logger对象作为代理，实际传给libLoader的logger api并发送给kotlin端
~~* koperation代理api，插件中进行操作时，实际传递给koperation进行操作~~

以上部分可能有一些是不必要的，或者仍未考虑周全的，先一步步做测试

### 组件选择

both

**Comment by Nambers** [comment]
初步设计流程

1. mcl / loader加载miraicp kotlin端 -> kotlin端 PublicShared.onEnable -> 初始化CPPLib -> System.load libloader(初步定为在resource内) -> 调用Verify, 传入当前miraicp版本用于校验, 以及建议传入jar目前绝对路径如果有路径问题
所以 Verify 接受2个string参数, 返回 void

3. console 接收到input命令 -> 解析内建命令 -> 共用Event接口传递数据到libloader, 因为插件列表由libloader维护, 有这几种情况:
   - plist, 返回全部插件信息
   - disable, 禁用插件
   - enable, 启用插件
   - dlist, 全部禁用插件列表
   - load
   - reload
   - unload'
  -> 可不返回
所以 Event 接口至少传入一个string, 返回 void

4. kt接收到事件 -> 序列化 -> 用Event接口
所以Event 接口只需要传入一个String, 返回void, 如果有异常直接print出去就行

5. kt disable -> disable 接口
所以disable接口不需要返回和传参

以上为loader和plugin的方案, 此外需要注意core的方案, 我倾向于维持现状, 但是由于core本身不需要libloader, 这边还要小改

@Antares0982

**Comment by Antares0982** [comment]
#71 同时把插件权限加上，插件权限高的可以控制其他插件或自身的加载、禁用等，权限低的不能控制其他插件加载
