### ISSUE TITLE
减少插件以及libloader体积

### ISSUE THREAD

**Issue by Nambers** [Nambers/MiraiCP#115]
### 功能描述

可能分离MiraiCP里的依赖到libloader

### 原因

_

### 组件选择

both

**Comment by Antares0982** [comment]
简单记录一下分离插件端实现的计划（构思）：
* 在linux上（以及mac应该也是），只需要将重复的符号全部转入libloader部分即可，不需要链接libLoader.so；libLoader编译时使用-rdynamic参数保证符号表在插件也可见。运行时通过dlopen()打开插件，插件理论上会读到libloader的符号
* Windows上编译时需要链接libLoader.dll以正常寻找符号。相对路径等问题需要更多的测试
