### ISSUE TITLE
libloader测试

### ISSUE THREAD

**Issue by Antares0982** [Nambers/MiraiCP#118]
### 功能描述

libloader功能还没有测试完，想到什么就直接编辑加条目吧

- [x] 测试在事件中和onexit抛出异常
- [x] 测试在各种情况下结束kt进程时libloader能否正常卸载并且不报sigsegv
- [x] 测试修改后的loader api功能是否正常

其他可以在单元测试做的就在单元测试做

### 原因

测试，测试不做就会有一堆issue，比如119和121（

**Comment by Antares0982** [comment]
目前发现插件加载失败时没有从内存中卸载掉， #119 的报错

**Comment by Antares0982** [comment]
以及，kt端可能需要考虑一下处理接收到的SIGINT（与ctrl+C输入等同）

**Comment by Nambers** [comment]
todo:
- [ ] deadlock with kt exit thread and getPluginInfo in onEnable
- [ ] try to call onExit in exception handler
