### ISSUE TITLE
希望定时任务除了id外，增加void指针的参数，这样就不必用全局变量来调用了

### ISSUE THREAD

**Issue by ARKMIO** [Nambers/MiraiCP#12]

**Comment by Nambers** [comment]
可能不会用void*类型，因为不能序列化，可能考虑增加类重载

**Comment by Nambers** [comment]
本来想用template重载的，但还是改成传入initalize_list<string>然后返回给你们，你们在事件里用atoi自己解析成想要的类型然后传入用to_string，否则可能会需要在代码里重载所有可能的值

**Comment by Nambers** [comment]
会在今晚发布的v2.6.0增加
