### ISSUE TITLE
2.12 使用 libloader在事件触发时会导致mcl崩溃

### ISSUE THREAD

**Issue by syokanatsu** [Nambers/MiraiCP#121]
### Code of Conduct

- [X] I conform

### 问题描述

2.12 使用 libloader在事件触发时会导致mcl崩溃
![image](https://user-images.githubusercontent.com/50983420/180106952-46c56ea6-e5bd-4115-b3e1-d21b867492aa.png)

### 版本

2.12.0

### 组件

LibLoader

**Comment by syokanatsu** [comment]
![image](https://user-images.githubusercontent.com/50983420/180107354-dd032f9a-cec7-451a-9c7c-e72faa67497e.png)

**Comment by Nambers** [comment]
> ![image](https://user-images.githubusercontent.com/50983420/180107354-dd032f9a-cec7-451a-9c7c-e72faa67497e.png)

问题同 #119

**Comment by Antares0982** [comment]
#120

**Comment by syokanatsu** [comment]
是release现在不能用吗？我要吧libloader打包成debug？

**Comment by Antares0982** [comment]
> 是release现在不能用吗？我要吧libloader打包成debug？

等这个仓库更新 https://github.com/Nambers/MiraiCP-devReleases/tree/main/dev

**Comment by Nambers** [comment]
> 是release现在不能用吗？我要吧libloader打包成debug？

https://github.com/Nambers/MiraiCP-devReleases/tree/main/fix_issues  可以试一下这个

**Comment by Nambers** [comment]
> 是release现在不能用吗？我要吧libloader打包成debug？

https://github.com/Nambers/MiraiCP-devReleases/tree/main/fix_issues  可以试一下这个

**Comment by syokanatsu** [comment]
> > 是release现在不能用吗？我要吧libloader打包成debug？
> 
> https://github.com/Nambers/MiraiCP-devReleases/tree/main/fix_issues 可以试一下这个

不行，debug生成的dll报这个错误

**Comment by syokanatsu** [comment]
> > 是release现在不能用吗？我要吧libloader打包成debug？
> 
> https://github.com/Nambers/MiraiCP-devReleases/tree/main/fix_issues 可以试一下这个

刚刚用错了dll，测试了这个可以了！

**Comment by Antares0982** [comment]
> > > 是release现在不能用吗？我要吧libloader打包成debug？
> > 
> > 
> > https://github.com/Nambers/MiraiCP-devReleases/tree/main/fix_issues 可以试一下这个
> 
> 刚刚用错了dll，测试了这个可以了！

目前先不要call libloader api，可能会崩，如果之后遇到任何问题欢迎随时反馈
