### ISSUE TITLE
libloader加载dll失败，loadlibrary失败

### ISSUE THREAD

**Issue by syokanatsu** [Nambers/MiraiCP#124]
### Code of Conduct

- [X] I conform

### 问题描述

libloader加载dll失败（是loadlibrary失败，不是获取函数地址），自测程序加载dll没有问题
![image](https://user-images.githubusercontent.com/50983420/181012737-1ea6200a-d6e1-4849-b6ab-d2549f5c3630.png)
![image](https://user-images.githubusercontent.com/50983420/181012742-c7ab34fc-0263-4c92-8db0-51d1679d825a.png)

### 版本

2.12RC

### 组件

LibLoader

**Comment by Nambers** [comment]
使用`v2.12-rc2`试一下

**Comment by syokanatsu** [comment]
发现问题了，原来是工作目录搞错了，第三方库依赖需要放到根目录，而不是dll的目录
