### ISSUE TITLE
安装MiraiCP-Plugin后报错

### ISSUE THREAD

**Issue by Shuaiguozi** [Nambers/MiraiCP#127]
### Code of Conduct

- [x] I conform

### 问题描述

利用该指令进行MiraiCP-Plugin插件安装后再次运行mcl报错
`mcl --update-package io.github.nambers:MiraiCP-plugin --channel nightly --type plugin`

报错内容：
![image](https://user-images.githubusercontent.com/49605891/189937204-cac6252c-7cf7-46c7-914e-ba55e8259e30.png)

### 版本

Latest

### 组件

Plugin

**Comment by Nambers** [comment]
试一下不用mcl的自动下载: 在config.json中去掉miraicp那一项，然后从release里面手动下载.mirai2.jar 放到plugins 文件夹里面
