### ISSUE TITLE
接收到消息时jdk停止工作，可能是因为解析消息

### ISSUE THREAD

**Issue by lesser0** [Nambers/MiraiCP#136]
### Code of Conduct

- [x] I conform

### 问题描述

如图jdk停止工作，停止前最后一条消息如附图。近期隔几天就会发生一次，但之前没有打开全部等级日志导致原因不明，附图是打开全日志后目前第一次出现。目前仍然保持日志打开，如果再出现也会更新日志进来。
看起来比较可疑的是messageChain内容为空？测试过正常的合并转发，无论是表情还是上传的图片，messageChain都应该有内容。不知空内容是否会导致解析失败。可能是图片被腾讯屏蔽？也可能和这是合并转发的消息有关？
![日志](https://s2.loli.net/2022/10/11/3iRyDkATIsbvudj.png)

### 日志

```text
[0m2022-10-11 22:30:49 V/Bot.【bot id】: [【名字】，(【id】)] 【名字】（【名字】）(【id】) -> [mirai:origin:FORWARD,GCM3CicS2v+csF8mROXOIU2cOHs979zrZeNhP5+oHL+Fx7qUA192mwxzruOSEU6v]ForwardMessage(preview=[【名字】:  [文件]246.png, 【名字】:  [文件]242.png], title=【名字】的聊天记录, brief=[聊天记录], source=聊天记录, summary=查看2条转发消息, nodeList=[Node(senderId=【id】, time=1665480110, senderName=【名字】, messageChain=), Node(senderId=【id】, time=1665480582, senderName=【名字】, messageChain=)])[0m[m

【】内是隐去的id和名字
```

### 版本

v2.12.0-RC2

### 组件

Plugin

**Comment by Antares0982** [comment]
崩溃一般是Access Violation，以debug模式编译插件并将dump日志发上来。如果有可能的话，可以试试 https://github.com/Antares0982/MiraiCP-debug-docs 以debug模式编译libloader并且用ide挂上去看

**Comment by Antares0982** [comment]
以及可以的话发一下你觉得相关的可能代码段，方便排查

**Comment by lesser0** [comment]
出现频率很低，几天发生一次，于是只能在服务器上运行等待复现，服务器上ide估计跑不起来。
我先等复现观察日志看看。

**Comment by lesser0** [comment]
发现可能原因是
合并转发的消息事件的MessageChain message成员调toMiraiCode()的返回值会是空的
然后后续我的代码预设了接收到的消息非空。

目前加了检验空消息的保护，观察看看是否还会出现这问题。
如果是这原因的话，那就不是miraicp的bug，但建议这种情况调toMiraiCode()的话抛个异常或者怎么样提醒一下？

**Comment by Antares0982** [comment]
https://github.com/Nambers/MiraiCP/blob/a01dca14c953137b4481bab843f5346318d69c02/cpp/src/include/ForwardedMessage.h#L169-L172

是指这个吗，如果是的话建议你改一下代码，判断一下

**Comment by lesser0** [comment]
啊是的，理论上是这里得到空消息会导致问题。已经加了检验，看是否还会出现问题。

顺带一问，我在这里用到toMiraiCode()也不是为了发送消息，而是收到的消息转换为字符串用于后续处理。那看注释这设计只为发送的话，是否有别的方法在接收时转换？

**Comment by Antares0982** [comment]
用这个

https://github.com/Nambers/MiraiCP/blob/a01dca14c953137b4481bab843f5346318d69c02/cpp/src/include/ForwardedMessage.h#L167

之后转发消息这里的逻辑可能会在下个版本更新

**Comment by Antares0982** [comment]
examples 参考 https://github.com/Nambers/MiraiCP/blob/a01dca14c953137b4481bab843f5346318d69c02/cpp/src/examples/forwardedMessage.cpp

**Comment by Antares0982** [comment]
```c++
auto messageString = onlineForwardedMessage.toForwardedMessage().nodesToJson().dump();
```
