### ISSUE TITLE
使用SendMiraiCode()发送图片会导致java虚拟机在发送后崩溃(loader)

### ISSUE THREAD

**Issue by Zipper-1** [Nambers/MiraiCP#14]

**Comment by Zipper-1** [comment]
jvm's log;[https://raw.githubusercontent.com/Zipper-1/MiraiCP/master/.github/ISSUE_TEMPLATE/hs_err_pid.log](url)

**Comment by Nambers** [comment]
提供下调用sendmiraicode那部分代码？和版本

**Comment by Zipper-1** [comment]
> 提供下调用sendmiraicode那部分代码？和版本

mitaiCP 2.4.6
java1.8和jdk15均有此问题
pp.sender.SendMiraiCode("[mirai:image:{036820C0-22C0-7CB1-FC44-04C15CE30D8C}.jpg]");

**Comment by Nambers** [comment]
> > 提供下调用sendmiraicode那部分代码？和版本
> 
> mitaiCP 2.4.6
> java1.8和jdk15均有此问题
> pp.sender.SendMiraiCode("[mirai:image:{036820C0-22C0-7CB1-FC44-04C15CE30D8C}.jpg]");

jstring转码报的问题，可能是因为当前图片序列号不存在

**Comment by Nambers** [comment]
在2.5.0中修复
