### ISSUE TITLE
C++多线程到底应该如何调用。。。

### ISSUE THREAD

**Issue by ARKMIO** [Nambers/MiraiCP#15]
新创建的线程不能调用任何kotlin部分代码，包括logger和定时任务。

消息回调中不能执行延迟任务，所以我把延时任务放到了定时任务，但是，定时任务执行任务需要回调传递参数，用全局变量就必须加锁，但是，他们属于同一线程，后来考虑是同一携程，只使用一个变量来协调公共资源访问还是会出问题。

尝试多线程后，新开的工作线程没法调用这边任何的函数（包括定时任务）来帮助发送消息。甚至logger->Info执行就会直接闪退。我该如何是好。

**Comment by Nambers** [comment]
新开的线程无法访问是以为JNIEnv不能在进程见共享的问题，我应该是在example.md里写了，你也可以搜一下，如果一定要用就要换成JNIvm这个对象，然后在多线程里用getEnv()获取，这个以后可能会考虑加或者你自己写进去也可以，不过挺麻烦的，我之前本来打算写，大概就在onLoad()里获取到JNIvm，然后定时任务那我认为可以把需要传递的都写成参数而不是全局变量传进去，比如传3个变量，1是你接下来要执行什么，比如发送信息我就传入1，禁言就2，比如是1，然后下一个参数就传发送好友的id，用to_string()转换成string，然后下一个就传前面那个参数的类型，比如long我设定成1，就传1，然后用stoi()转换成long类型(或者如果固定的话就不用传直接在对应命令解)，亦或者直接传个json，然后用jsoncpp解析什么的

**Comment by Nambers** [comment]
其实主要看你多线程要执行什么任务吧，说下看看？

**Comment by ARKMIO** [comment]
example.md里看了，以为指的是在其他线程里面能调用定时任务。因为消息回调里面基本做不了什么，网络请求会直接失败，然后之前我做法是全都放在定时任务里面了。经常报错不是当前线程什么的，不过勉强能用。
我现在的做法是，回调触发后根据group_id，把任务分发给工作线程，然后工作线程处理具体事务，比如拿个色图，根据之前的消息复读，拿微博爬的数据，从NLP服务里面拿回复等等。然后最后调用定时任务发送处理结果，这么设想的，完成之后，发现确实拿不到JNINnv，然后问一下有没有好的办法的。那我尝试一下去换成JNIvm吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eritque ***@***.***&gt;; 
发送时间: 2021年3月17日(星期三) 晚上8:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Nambers/MiraiCP] C++多线程到底应该如何调用。。。 (#15)





 
其实主要看你多线程要执行什么任务吧，说下看看？
 
&mdash;

**Comment by Nambers** [comment]
原本在我设想里，在lambda里应该是可以和普通function相同作用的，所有我就选择了这个方案，就传到kt返回当成事件处理，多线程的作用是防止运行过慢？那确实可能应该缓存jnivm对象更简单，不过我之前试了下好像有点复杂，就没有细写，以后有时间可能会加

**Comment by Nambers** [comment]
@ARKMIO 看<b1208a863c57f7e34153cb2620be464da9126596>大概是这样子写

**Comment by Nambers** [comment]
应该会在v2.4.7增加详细调用接口

**Comment by Nambers** [comment]
在2.5.0中，文档中也会新增案例
