### ISSUE TITLE
MemberJoinEvent

### ISSUE THREAD

**Issue by wly20040415** [Nambers/MiraiCP#158]
### Code of Conduct

- [X] I conform

### 问题描述

MemberJoinEvent接受不到成员进入群聊的事件

### 日志

```text
null
```

### 版本

MiraiCP-plugin-2.13.0-alpha-3

### 组件

LibLoader

### 编译器

Microsoft Visual C++ (MSVC)

### 系统

Windows

### 架构

arm64/aarch64

**Comment by Nambers** [comment]
确认一下: 你那边可以多次复现 + 有报错信息或者什么特殊条件之类的吗

**Comment by Nambers** [comment]
> > 确认一下: 你那边可以多次复现 + 有报错信息或者什么特殊条件之类的吗
> 
> 没有报错信息，就是我在注册好进群事件以后，写了一个简单的进群提醒，但是在运行机器人后新人进群会没有反应

okok 群人数呢
