### ISSUE TITLE
群头衔

### ISSUE THREAD

**Issue by ofbwyx** [Nambers/MiraiCP#168]
### 功能描述

希望能有获取群员的群头衔和更改群头衔的事件。

### 原因

希望能有获取群员的群头衔和更改群头衔的事件。

### 组件选择

both

**Comment by ofbwyx** [comment]
顺带一提为什么文档里边的示例都看不了了（

**Comment by Nambers** [comment]
> 顺带一提为什么文档里边的示例都看不了了（

修好了 72930a3d85865d9b74bc8dca1dc7c4d656c62223
