### ISSUE TITLE
miraicode解析对at出错

### ISSUE THREAD

**Issue by lesser0** [Nambers/MiraiCP#174]
### Code of Conduct

- [X] I conform

### 问题描述

MessageChain MessageChain::deserializationFromMiraiCode(const std::string &m)
中不应有
```
if (t == 1)
    lastPos++;
```
且如果at的miraicode后直接接中文的话，缺少一个字节会导致不符合utf8编码，于是在之后的json的dump()中出错。

### 版本

v2.13.2

### 组件

Plugin(SDK)

### 编译器

Microsoft Visual C++ (MSVC)

### 系统

Windows

### 架构

x86-64/amd64

**Comment by Nambers** [comment]
提供一些可能的 MiraiCode 文本? 我用来测试

**Comment by lesser0** [comment]
比如
`"（[mirai:at:任意qq号]）"`
不过是不是不需要了（
