### ISSUE TITLE
version `GLIBC_2.33' not found 

### ISSUE THREAD

**Issue by cmuCoppelia** [Nambers/MiraiCP#178]
### Code of Conduct

- [X] I conform

### 问题描述

Exception in thread "main" java.lang.UnsatisfiedLinkError: /root/qq/MiraiCP-template/libLoader.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /root/qq/MiraiCP-template/libLoader.so)

我的glibc版本是2.31，请问是否有使用2.31的版本呢？

### 版本

2.13.2

### 组件

Loader(java)

### 编译器

gcc/g++

### 系统

Linux/Unix

### 架构

x86-64/amd64

**Comment by Nambers** [comment]
这个的原因是我们 CI 使用的环境和你本身的不匹配/不兼容
所以目前来说, 你可以自己编译一份 libLoader
步骤如下(参考<https://github.com/Nambers/MiraiCP/blob/dev/.github/workflows/releases.yml>):
1. git clone 本项目然后 cd 进
2. `mkdir cpp/build && cd cpp/build && cmake -DCMAKE_BUILD_TYPE=Release -DGOOGLE_TEST=OFF ..`
3. 保持在 build 目录然后 `make Loader`
4. 然后在 build 目录下有
如果你有什么建议也可以在本issue探讨, 比如我们用什么方式支持不同的环境版本之类的.
目前来说就是自己编译一份

**Comment by Antares0982** [comment]
fixed in 516d8a3
