### ISSUE TITLE
想问应该如何恰当实现定时任务

### ISSUE THREAD

**Issue by Wrg1t** [Nambers/MiraiCP#179]
### 功能描述

请问目前的MiraiCP(2.13.2)应该怎么恰当地实现定时任务？不是`schedule()`后`在一定时间后广播**一次**TimeOutEvent`的形式，希望的是可以实现类似[JavaPluginScheduler](https://github.com/mamoe/mirai/blob/dev/mirai-console/backend/mirai-console/src/plugin/jvm/JavaPluginScheduler.kt)中`repeating()`的功能，即每经过一定的时间执行一次给定任务。
(实在找不到比较恰当的地方提issue，希望大佬谅解。)

### 原因

为了及时抓取信息源并与已存储的信息比较，所以需要在一定间隔后再执行。

### 组件选择

plugin

**Comment by Antares0982** [comment]
你可以在注册timeoutEvent处解析content，然后再次发送一个schedule()
```c++
Event::registerEvent<TimeOutEvent>([](TimeOutEvent a){
            if(a.msg=="repeat"){
                schedule(10, "repeat");
                // do your job
            }
        });
```

**Comment by Wrg1t** [comment]
> 你可以在注册timeoutEvent处解析content，然后再次发送一个schedule()
> 
> ```c++
> Event::registerEvent<TimeOutEvent>([](TimeOutEvent a){
>             if(a.msg=="repeat"){
>                 schedule(10, "repeat");
>                 // do your job
>             }
>         });
> ```
有道理啊！感谢。
