### ISSUE TITLE
多线程用最初那个方案是可以的，之后更新的

### ISSUE THREAD

**Issue by ARKMIO** [Nambers/MiraiCP#18]
消息回调中消息编码从UTF-8转成了gb2312，看来我之前写的编码部分又要改了，虽然已经猜到之前issue提到的乱码是指的编码问题，都是小事。
多线程最开始改的那个是可以用的，后面更新一次，把全局genv赋值放到getEnv中就没法反向调用kotlin了，啊这。

**Comment by Nambers** [comment]
> 消息回调中消息编码从UTF-8转成了gb2312，看来我之前写的编码部分又要改了，虽然已经猜到之前issue提到的乱码是指的编码问题，都是小事。
> 多线程最开始改的那个是可以用的，后面更新一次，把全局genv赋值放到getEnv中就没法反向调用kotlin了，啊这。

az 我去试一下，目前全部编码都统一到utf8了

**Comment by ARKMIO** [comment]
我试了几下，发现和genv赋值位置无关
args.group = (jobject)tools.str2jstring(threadGroupName); 
这个语句炸了

**Comment by Nambers** [comment]
> 我试了几下，发现和genv赋值位置无关
> args.group = (jobject)tools.str2jstring(threadGroupName);
> 这个语句炸了

找到原因了，传了个NULL到strlen里，改这个有几种方法
1. 在str2jstring里加非空判断
2. 把getEnv里的参数从NULL改到""

**Comment by Nambers** [comment]
多线程支持可能要晚点才能出，设计有点复杂，因为attach后要detach，但是detach又影响到了genv，然后因为线程结束后还有地方要用到genv，所以在线程结束后还要确保genv可用

**Comment by Nambers** [comment]
#19

**Comment by Nambers** [comment]
会在v2.5.0-patch-1发布

**Comment by Nambers** [comment]
已更新

**Comment by Nambers** [comment]
已更新
