### ISSUE TITLE
通过MessageSource获取发送人、消息内容等信息

### ISSUE THREAD

**Issue by singer01** [Nambers/MiraiCP#180]
### 功能描述

通过MessageSource获取发送人、消息内容等信息

### 原因

需要获取QuoteReply的发送人

### 组件选择

plugin

**Comment by Nambers** [comment]
获取消息内容可以用 source 属性调用 `MessageChain::deserializationFromMessageSourceJson`, 或者直接在 source 里取 originalMessage 然后用 `MessageChain::deserializationFromMessageJson`.

`MessageChain::deserializationFromMessageSourceJson` 包含可能的错误实现, 因为我打算弃用他也就没怎么做测试和维护这个方法了. 
然后因为 MessageSource 的内容有些复杂, 我暂时可能不会考虑实现获取发送人之类的
1. 你可以自己实现一个结构体, 里面包含发送人, 然后你存的时候自己赋值
2. 你可以自行解析 MessageSource 里的内容, 格式是 json, 然后结构如 [MessageSource.kt](https://github.com/mamoe/mirai/blob/v2.13.4/mirai-core-api/src/commonMain/kotlin/message/data/MessageSource.kt) 所示
