### ISSUE TITLE
schedule 占用 cpu 过多

### ISSUE THREAD

**Issue by ofbwyx** [Nambers/MiraiCP#181]
### Code of Conduct

- [X] I conform

### 问题描述

相同的代码，正常运行时平均 cpu 占用在 20% 以下，在代码中加入 schedule 之后会直接飙到 100%（1 核的渣服务器）。

### 版本

2.13.2

### 组件

不属于上述项或我不知道属于哪一项

### 编译器

Microsoft Visual C++ (MSVC)

### 系统

Windows

### 架构

x86-64/amd64

**Comment by Antares0982** [comment]
能否在dev分支自行编译一下libloader试试这个问题还能否复现？之前的tick逻辑有问题现在dev分支已经改掉了

**Comment by Antares0982** [comment]
经测试该问题已经在dev分支修复
