### ISSUE TITLE
优化多线程支持

### ISSUE THREAD

**Issue by Nambers** [Nambers/MiraiCP#19]
因为要线程间互不干扰，所以线程中可能不能使用genv全局env，因为有风险
1. 线程可能在主线程执行完后还执行，而主线程执行完后genv失效，无法确保主线程可以正确执行
2. 如果覆盖genv，主线程可能在线程执行完后继续执行(如用.join())，那genv在线程执行完后就失效，无法确保主线程后的内容正确执行

所以在v2.5.0-patch-1中，线程最好手动传入env参数而不是使用genv，接下来会想办法简化

**Comment by ARKMIO** [comment]
我不知道env可不可以有多个，所以我之前做法是，多线程只在处理完最后要发消息时加锁换env，发完消息解除然后解锁。 群消息回调只负责往消费队列中添加任务，如果可以有多个env当然更方便。

**Comment by Nambers** [comment]
> 我不知道env可不可以有多个，所以我之前做法是，多线程只在处理完最后要发消息时加锁换env，发完消息解除然后解锁。 群消息回调只负责往消费队列中添加任务，如果可以有多个env当然更方便。

其实主要是JNIEnv*指针指向的内容会在detach操作或者JNIcall函数结束后释放，也就是说是局部的某种意义上，然后我们好像没办法判断JNIEnv还有没有用

**Comment by ARKMIO** [comment]
如果要继续用全局话，可以把genv封装成一个单例类，记录当前使用的线程ID号和状态，在每次detach之后标记为detach状态，然后线程就可以通过这个类知道它当前是否有效。

**Comment by Nambers** [comment]
> 如果要继续用全局话，可以把genv封装成一个单例类，记录当前使用的线程ID号和状态，在每次detach之后标记为detach状态，然后线程就可以通过这个类知道它当前是否有效。

确实可以，可能会在v2.5.1实现

**Comment by Nambers** [comment]
多线程优化实现已在 de4acbd 基本全部完成，不过目前还有个问题 #31 ，修复后会发布包含多线程优化的版本v2.5.1
