### ISSUE TITLE
BotOnline事件不触发

### ISSUE THREAD

**Issue by surf08** [Nambers/MiraiCP#194]
### Code of Conduct

- [X] I conform

### 问题描述

RT
Mirai是2.15.0-M1

### 版本

2.15.0-RC2

### 组件

Plugin(SDK)

### 编译器

Microsoft Visual C++ (MSVC)

### 系统

Windows

### 架构

x86-64/amd64

**Comment by Nambers** [comment]
看看代码

**Comment by surf08** [comment]
![1](https://github.com/Nambers/MiraiCP/assets/105436365/712c3b2f-4ae0-432d-8df3-51c38969a65b)
![2](https://github.com/Nambers/MiraiCP/assets/105436365/884eb4ef-803b-4d79-88f3-2ac18d67d01c)

**Comment by Nambers** [comment]
我本地无法复现此问题，用 mcl 可以触发 OnlineEvent
```
void onEnable() override {
        Logger::logger.info("loading test plugin!A");
        Event::registerEvent<BotOnlineEvent>([](BotOnlineEvent a) {
            Logger::logger.info("bot online!");
        });
    }
```

**Comment by surf08** [comment]
今天更新RC版就好了，貌似2.15.0-M1这版mirai的问题
