### ISSUE TITLE
更新java -jar MiraiCP.jar -g生成的config

### ISSUE THREAD

**Issue by Antares0982** [Nambers/MiraiCP#201]
### Code of Conduct

- [X] I conform

### 问题描述

`java -jar MiraiCP-loader-<version>.jar -g`生成的配置文件已经过时。除此之外，在打印完
```
使用 -g 可以生成config.json模板(java -jar MiraiCP-loader-<version>.jar -g)
```
之后，程序应当立刻退出。

### 版本

v2.16.0-dev1

### 组件

Loader(java)

### 编译器

其他

### 系统

其他

### 架构

其他

**Comment by Nambers** [comment]
是直接退出的
