### ISSUE TITLE
recall函数无法撤回图片类消息

### ISSUE THREAD

**Issue by Zipper-1** [Nambers/MiraiCP#50]
使用recall函数撤回图片消息失败，报无法解析的json中"Image"的消息类型，怀疑可能是mirai主程序问题（但我不想看代码）

**Comment by Nambers** [comment]
我看看

**Comment by Nambers** [comment]
确实有这个问题，我去mirai那问下看看

**Comment by Nambers** [comment]
https://github.com/mamoe/mirai/issues/1273

**Comment by Nambers** [comment]
已获取答复，会在v2.6.3修复
