### ISSUE TITLE
如何发送Emoji表情?

### ISSUE THREAD

**Issue by jshintrc** [Nambers/MiraiCP#59]
e.group.SendMsg("\uD83D\uDE03");

我按照例子写的代码，直接就报错了EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007fff8c1f3b19, pid=8456, tid=13796

**Desktop (please complete the following information): 描述本地运行环境**
 - JavaVersion 16.0.1
 - MiraiVersion Mirai版本 [v2.6.3]

**Comment by Nambers** [comment]
报错前日志看看?

**Comment by jshintrc** [comment]
以下是详细的日志

https://raw.githubusercontent.com/jshintrc/MiraiCP/main/hs_err_pid8456

**Comment by jshintrc** [comment]
// 监听群信息
procession->registerEvent<GroupMessageEvent>([=](GroupMessageEvent e) {
  e.group.SendMsg("\u0032\u20E3");
}

**Comment by Nambers** [comment]
欸我是说打印在mcl/loader里的日志，你尽量看看有没有，如果没有就算了，我明天试一下复现
你可以先用qqface看看

**Comment by jshintrc** [comment]
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007fff8c1f3b19, pid=8456, tid=13796
#
# JRE version: Java(TM) SE Runtime Environment (16.0.1+9) (build 16.0.1+9-24)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (16.0.1+9-24, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [KERNELBASE.dll+0x43b19]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# E:\mcl\hs_err_pid8456.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

**Comment by jshintrc** [comment]
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007fff8c1f3b19, pid=8456, tid=13796
#
# JRE version: Java(TM) SE Runtime Environment (16.0.1+9) (build 16.0.1+9-24)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (16.0.1+9-24, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [KERNELBASE.dll+0x43b19]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# E:\mcl\hs_err_pid8456.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

**Comment by jshintrc** [comment]
mcl 里面报错的信息, 如上!

**Comment by Nambers** [comment]
是有这个问题，明天修

**Comment by Nambers** [comment]
已修复，在下一个版本附加上

**Comment by Nambers** [comment]
已发v2.6.4 https://github.com/Nambers/MiraiCP/releases/tag/v2.6.4
