### ISSUE TITLE
构建内核

### ISSUE THREAD

**Issue by Nambers** [Nambers/MiraiCP#6]
目前Plugin和Loader里基本重复，可把里面的内容提取出来构成jar内核包从而减轻同步更改的工作量，且使得热更新成为可能

**Comment by Nambers** [comment]
原本计划是把CPP_lib，PluginMain以及Config移动到Core使用idea打包到jar包被主程序动态引入，但是遇到了如下几个问题:
1.  C++部分jni需要取得CPP_lib类，但是CPP_lib类在依赖里无法取到，计划暂时变更为CPP_lib类中被jni部分调用的写在主程序，CPP_lib调用jni部分写在Core
2. PluginMain类中数据缓存以及其他若干错误
3. Config可正常转移
4. 动态引用需要每个方法都写一次，计划暂时变更为用gradle引入(compile)本地jar包

**Comment by Agoines** [comment]
冒昧问一下，这个库是用来干嘛的

**Comment by Nambers** [comment]
> 冒昧问一下，这个库是用来干嘛的

嗯？哪个

**Comment by Agoines** [comment]
> > 冒昧问一下，这个库是用来干嘛的
> 
> 嗯？这个内核计划？
> 我计划就相当于构建个mirai-console和mirai-core的关系
> 主要是目前miraicp-plugin和miraicp-loader有大量重复代码
> 且这个库如果实现可以实现热更新，就相当于mcl那种，打开自动下载库更新，而不需要每次来github上下载替换一些文件
> 不过目前精力不够只能先放一会

明白了，

**Comment by Nambers** [comment]
使用gradle子项目的方法实现
