### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 1328649047** [Nambers/MiraiCP#67]
是编译后有个cpp.dll  之后放在dll目录中吗
但好像好像没有什么用

**Comment by Nambers** [comment]
cpp.dll  是顺便放到目录，在config.json里写cpp.dll的路径
怎么用看首页readme里使用方法
https://github.com/Nambers/MiraiCP#3-%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by 1328649047** [comment]
写过了   是写文件路径 还是目录路径

**Comment by Nambers** [comment]
文件
是loader还是plugin，版本是?

**Comment by Nambers** [comment]
文件路径
是loader还是plugin，版本是?

**Comment by 1328649047** [comment]
loader   原来如此  那是何填多个dll文件

**Comment by 1328649047** [comment]
最新版

**Comment by Nambers** [comment]
是什么问题 没加载dll? 还是什么，还有日志有什么异常报告吗?

**Comment by 1328649047** [comment]
已经好了
我之前填的文件夹路径 以为它可以在文件夹下面放很多dll   类似与web服务器配置文件那种

**Comment by Nambers** [comment]
> 已经好了
> 我之前填的文件夹路径 以为它可以在文件夹下面放很多dll 类似与web服务器配置文件那种

qs 以后应该会做成自动监测文件夹下全部dll, 然后全部加载
不过现在还不能同时加载多个dll作为插件
