### ISSUE TITLE
敏感api支持

### ISSUE THREAD

**Issue by Nambers** [Nambers/MiraiCP#73]
考虑要不要支持敏感api，如在插件中增加登录bot和加载插件api
需求应该不是很大，优先级不会很高
可选发展

**Comment by tsurumi-yizhou** [comment]
期望支持

**Comment by Nambers** [comment]
> 期望支持

这个大概是有什么用途吗？ 我没想到什么可能的用途
如果要加这个，由于他可能是不安全的，所以要引入配置文件权限设置，从而会增加配置文件的复杂度，所以我要评估下要不要加
🤔
