### ISSUE TITLE
quit()报错

### ISSUE THREAD

**Issue by Antarcticann** [Nambers/MiraiCP#79]
**Describe the bug 描述出现的异常(实际行为和预期行为)**
在调用e.group.quit()之后报错，如下
**Screenshots 相关代码和日志截图或复制上来**

> 2021-09-07 12:06:41 I/stdout: JSONObject["source"] not found.
> 2021-09-07 12:06:41 I/stdout: {"data":{"contactSource":"{\"botid\":3457317465,\"groupid\":0,\"id\":9*****0,\"nickornamecard\":\"柴*****家\",\"type\":2}","quit":true},"type":2}
> 2021-09-07 12:06:41 W/stderr: org.json.JSONException: JSONObject["source"] not found.
> 2021-09-07 12:06:41 W/stderr:   at org.json.JSONObject.get(JSONObject.java:572)
> 2021-09-07 12:06:41 W/stderr:   at org.json.JSONObject.getString(JSONObject.java:859)
> 2021-09-07 12:06:41 W/stderr:   at tech.eritquearcus.miraicp.shared.CPP_lib$Companion.KOperation(CPP_lib.kt:363)
> 2021-09-07 12:06:41 W/stderr:   at tech.eritquearcus.miraicp.shared.CPP_lib.KOperation(CPP_lib.kt)
> 2021-09-07 12:06:41 W/stderr:   at tech.eritquearcus.miraicp.shared.CPP_lib.Event(Native Method)
> 2021-09-07 12:06:41 W/stderr:   at tech.eritquearcus.miraicp.shared.UlitsKt$Event$$inlined$runInTP$1.invoke(Ulits.kt:72)
> 2021-09-07 12:06:41 W/stderr:   at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
> 2021-09-07 12:06:41 W/stderr:   at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
> 2021-09-07 12:06:41 W/stderr:   at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
> 2021-09-07 12:06:41 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 2021-09-07 12:06:41 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 2021-09-07 12:06:41 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 2021-09-07 12:06:41 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 2021-09-07 12:06:41 W/stderr:   at java.base/java.lang.Thread.run(Unknown Source)
> 2021-09-07 12:06:41 E/MiraiCP: MiraiCP error:MiraiCP内部无法预料的错误:

除此之外还有几个经常出现但没有导致程序崩溃的错误想问一下大佬
1.
> 2021-09-06 20:58:18 E/MiraiCP: json格式化异常,位置C-Handle
> 2021-09-06 20:58:18 E/MiraiCP: {"botid":3*****5,"from":{"botid":3457317465,"groupid":946029643,"id":843168503,"nickornamecard":"云*****屾","type":3},"tyoe":13,"type":null}
> 2021-09-06 20:58:18 E/MiraiCP: [json.exception.type_error.302] type must be number, but is null

2.
> 2021-09-06 20:58:32 W/stderr: org.json.JSONException: JSONObject["source"] not found.
> 2021-09-06 20:58:32 W/stderr:   at org.json.JSONObject.get(JSONObject.java:572)
> 2021-09-06 20:58:32 W/stderr:   at org.json.JSONObject.getString(JSONObject.java:859)
> 2021-09-06 20:58:32 W/stderr:   at tech.eritquearcus.miraicp.shared.CPP_lib$Companion.KOperation(CPP_lib.kt:363)
> 2021-09-06 20:58:32 W/stderr:   at tech.eritquearcus.miraicp.shared.CPP_lib.KOperation(CPP_lib.kt)
> 2021-09-06 20:58:32 W/stderr:   at tech.eritquearcus.miraicp.shared.CPP_lib.Event(Native Method)
> 2021-09-06 20:58:32 W/stderr:   at tech.eritquearcus.miraicp.shared.UlitsKt$Event$$inlined$runInTP$1.invoke(Ulits.kt:72)
> 2021-09-06 20:58:32 W/stderr:   at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
> 2021-09-06 20:58:32 W/stderr:   at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
> 2021-09-06 20:58:32 W/stderr:   at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
> 2021-09-06 20:58:32 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 2021-09-06 20:58:32 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 2021-09-06 20:58:32 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 2021-09-06 20:58:32 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 2021-09-06 20:58:32 W/stderr:   at java.base/java.lang.Thread.run(Unknown Source)
> 2021-09-06 20:58:32 E/MiraiCP: MiraiCP error:MiraiCP内部无法预料的错误:

3.
> 2021-09-06 20:56:03 E/miraiCP: Exception in coroutine Plugin miraiCP of miraiCP
> kotlinx.serialization.SerializationException: Class 'ForwardMessageInternal' is not registered for polymorphic serialization in the scope of 'SingleMessage'.
> Mark the base class as 'sealed' or register the serializer explicitly.
>         at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:102)
>         at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:113)
>         at kotlinx.serialization.PolymorphicSerializerKt.findPolymorphicSerializer(PolymorphicSerializer.kt:96)
>         at kotlinx.serialization.json.internal.PolymorphicKt.findActualSerializer(Polymorphic.kt:29)
>         at kotlinx.serialization.json.internal.PolymorphicKt.access$findActualSerializer(Polymorphic.kt:1)
>         at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:214)
>         at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
>         at kotlinx.serialization.internal.ListLikeSerializer.serialize(CollectionSerializers.kt:69)
>         at net.mamoe.mirai.message.data.MessageChain$Serializer.serialize(MessageChain.kt:266)
>         at net.mamoe.mirai.message.data.MessageChain$Serializer.serialize(MessageChain.kt:261)
>         at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:211)
>         at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
>         at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$SerialData$$serializer.serialize(MessageSerializersImpl.kt:41)
>         at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$SerialData$$serializer.serialize(MessageSerializersImpl.kt:41)
>         at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$special$$inlined$map$1.serialize(Serialization.kt:70)
>         at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl.serialize(MessageSerializersImpl.kt)
>         at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl.serialize(MessageSerializersImpl.kt:28)
>         at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:211)
>         at kotlinx.serialization.json.Json.encodeToString(Json.kt:80)
>         at tech.eritquearcus.miraicp.shared.PublicShared$onEnable$2.invokeSuspend(PublicShared.kt:921)
>         at tech.eritquearcus.miraicp.shared.PublicShared$onEnable$2.invoke(PublicShared.kt)
>         at tech.eritquearcus.miraicp.shared.PublicShared$onEnable$2.invoke(PublicShared.kt)
>         at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:432)
>         at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
>         at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
>         at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
>         at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
>         at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
>         at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
>         at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
>         at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
>         at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
>         at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:160)
>         at net.mamoe.mirai.internal.event.InternalEventListenersKt.callAndRemoveIfRequired(InternalEventListeners.kt:109)
>         at net.mamoe.mirai.event._EventBroadcast.broadcastImpl(Event.kt:174)
>         at net.mamoe.mirai.IMirai.broadcastEvent(IMirai.kt:312)
>         at net.mamoe.mirai.internal.MiraiImpl.broadcastEvent$suspendImpl(MiraiImpl.kt:304)
>         at net.mamoe.mirai.internal.MiraiImpl.broadcastEvent(MiraiImpl.kt)
>         at net.mamoe.mirai.event._EventBroadcast.broadcastPublic$suspendImpl(Event.kt:161)
>         at net.mamoe.mirai.event._EventBroadcast.broadcastPublic(Event.kt)
>         at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:148)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcast$2.invokeSuspend(EventDispatcher.kt:90)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcast$2.invoke(EventDispatcher.kt)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcast$2.invoke(EventDispatcher.kt)
>         at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
>         at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
>         at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broadcast$suspendImpl(EventDispatcher.kt:89)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broadcast(EventDispatcher.kt)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcastAsync$job$1.invokeSuspend(EventDispatcher.kt:105)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcastAsync$job$1.invoke(EventDispatcher.kt)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcastAsync$job$1.invoke(EventDispatcher.kt)
>         at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
>         at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
>         at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
>         at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
>         at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broadcastAsync-kKe4JaQ(EventDispatcher.kt:102)
>         at net.mamoe.mirai.internal.network.components.EventDispatcher.broadcastAsync-kKe4JaQ$default(EventDispatcher.kt:35)
>         at net.mamoe.mirai.internal.network.components.EventBroadcasterPacketHandler.impl(PacketHandler.kt:87)
>         at net.mamoe.mirai.internal.network.components.EventBroadcasterPacketHandler.handlePacket(PacketHandler.kt:73)
>         at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
>         at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:84)
>         at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
>         at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
>         at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
>         at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
>         at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
>         at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
>         at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
>         at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
>         at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
>         at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:82)
>         at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$2$1.invokeSuspend(NettyNetworkHandler.kt:186)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
>         at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
>         at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
>         at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
>         at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
>         at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
>         at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
>         at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
>         at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
>         at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
>         at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
>         at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
>         at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
>         at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
>         at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
>         at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

4.

> 2021-09-06 21:01:08 W/stderr: okhttp3.internal.http2.StreamResetException: stream was reset: REFUSED_STREAM
> 2021-09-06 21:01:08 W/stderr:   at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:148)
> 2021-09-06 21:01:08 W/stderr:   at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
> 2021-09-06 21:01:08 W/stderr:   at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
> 2021-09-06 21:01:08 W/stderr:   at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
> 2021-09-06 21:01:08 W/stderr:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
> 2021-09-06 21:01:08 W/stderr:   at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
> 2021-09-06 21:01:08 W/stderr:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
> 2021-09-06 21:01:08 W/stderr:   at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
> 2021-09-06 21:01:08 W/stderr:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
> 2021-09-06 21:01:08 W/stderr:   at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
> 2021-09-06 21:01:08 W/stderr:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
> 2021-09-06 21:01:08 W/stderr:   at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
> 2021-09-06 21:01:08 W/stderr:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
> 2021-09-06 21:01:08 W/stderr:   at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
> 2021-09-06 21:01:08 W/stderr:   at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
> 2021-09-06 21:01:08 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 2021-09-06 21:01:08 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 2021-09-06 21:01:08 W/stderr:   at java.base/java.lang.Thread.run(Unknown Source)
> 2021-09-06 21:01:08 E/MiraiCP: MiraiCP error:MiraiCP内部无法预料的错误:

如有打扰，请谅解
十分感谢！

**描述本地运行环境**
版本:

 - [x] plugin
 - [ ] loader
 - MiraiCP版本: `v2.7.0`

**Comment by Nambers** [comment]
okok 应该有几个是我的问题

**Comment by Nambers** [comment]
前几个都修了，我不知道为什么写出来的奇怪代码
后两个，第一个是我之前提过的issue，但是应该在2.7-M1就修了, 这个[issue](https://github.com/mamoe/mirai/issues/1289), 还在问
最后一个看起来像网络问题, 如果经常出现可以检查以下措施:
- 检查网络连通性和流量
- 增加线程池数量(我不确定可不可以), 参考配置文件doc: [doc](https://github.com/Nambers/MiraiCP/blob/master/doc/config.md#13-%E8%BF%9B%E9%98%B6%E9%85%8D%E7%BD%AE)

如果还是频繁出现再和我说下

**Comment by Antarcticann** [comment]
哦哦，我用的就是那个2.7.0版本的，从dev5直接覆盖了.hpp更新的，可能是我更新的不彻底Orz
quit()如果也是已经修复了的话我这就去试试
问了个好几个蠢问题(；д；)

**Comment by Nambers** [comment]
> 哦哦，我用的就是那个2.7.0版本的，从dev5直接覆盖了.hpp更新的，可能是我更新的不彻底Orz
> quit()如果也是已经修复了的话我这就去试试
> 问了个好几个蠢问题(；д；)

没 我在本地修了还没push上去 (

**Comment by Nambers** [comment]
试一下这个 [devRelease#79](https://github.com/Nambers/MiraiCP/tree/devRelease/%2379)

**Comment by Antarcticann** [comment]
哦哦哦！能正常工作了！辛苦大佬了！

**Comment by Nambers** [comment]
会在近几天发2.7.1-patch-1, 里面会包含这个修复和其他修复
