### ISSUE TITLE
通过g.SendMiraiCode(Image::uploadImg2Group(e.groupid, "***.jpg").toMiraiCode());发送的图片消息会多一个换行

### ISSUE THREAD

**Issue by ARKMIO** [Nambers/MiraiCP#8]

**Comment by Nambers** [comment]
你是指
![image](https://user-images.githubusercontent.com/35139537/110082947-0292b680-7dc9-11eb-956f-ffed17b15443.png)这种换行?
不过从发送出去的看是连在一起的
[mirai:image:{AB189090-1D76-D640-C1AE-92D1BFC1E107}.jpg]aaaa
而且从qq里好像也发送不出连在一起的？貌似

**Comment by ARKMIO** [comment]
就是单纯只发图片，下面总会多出一段空白，我试了一下，应该不是换行符，最后添加换行符，发送之后的效果也是没有白色边框的





好像是多了一个空白字符之类的？







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nambers/MiraiCP"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 下午3:41
收件人:&nbsp;"Nambers/MiraiCP"<MiraiCP@noreply.github.com&gt;;
抄送:&nbsp;"379173433"<379173433@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Nambers/MiraiCP] 通过g.SendMiraiCode(Image::uploadImg2Group(e.groupid, "***.jpg").toMiraiCode());发送的图片消息会多一个换行 (#8)





 
你是指
 这种换行?
 不过从发送出去的看是连在一起的
 [mirai:image:{AB189090-1D76-D640-C1AE-92D1BFC1E107}.jpg]aaaa
 而且从qq里好像也发送不出连在一起的？貌似

**Comment by Nambers** [comment]
那可能是我的问题
在刚刚的commit里我去掉了，如果要手动改的话是在image类的tomiraicode那的方括号后面有个空格
------------------ Original ------------------

**Comment by Nambers** [comment]
<https://github.com/Nambers/MiraiCP/commit/726f8cf99e6b5d728b22bbc6ccad9bdf9623a034>
