### ISSUE TITLE
消息撤回的回调中，RecallEvent类的ids和internalids为  [I@73be1feb 这种 JAVA中的整型数组地址

### ISSUE THREAD

**Issue by ARKMIO** [Nambers/MiraiCP#9]
procession->registerEvent([](RecallEvent e) {
       logger->Info(e.ids);
       logger->Info(e.internalids);

 I/miraiCP: [I@73be1feb
 I/miraiCP: [I@1c938388

**Comment by Nambers** [comment]
应该是修好了，在2.4.5发布的时候会带上，2.4.5预计这个星期内发布
